apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  labels:
    type: nfs
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
# mountOptions:
#   - nolock
  nfs:
    server: 172.30.28.112
    path: "/nodenfs/postgres-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
#  storageClassName: ""
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      type: nfs

